---

- name: Configuration for Production
  hosts: all
  become: yes
  vars:
    user_name: "vagrant"
    group_name: "www-data"

  roles:
    - common
    - python
    - { role: gunicorn, autostart: true, enabled: true }
    - { role: nginx, use_ssl: false, enabled: true }